### ISSUE TITLE
Roster Analysis Feature

### ISSUE THREAD

**Issue by barrytarter** [EXACTsports/roster-project#4]
Check out https://docs.google.com/document/d/13T6oDexWh-dXtDSYZLBXAxn5T3EP9F88Ul2i2ls3B30/edit as this is the 2nd stage of collecting the data. Get as much of this project completed by Sunday as you can, as we'll begin a new project on Monday (using Spotify API).

Please try your best to finish this project of automating the functionality for getting all athletes social data AND now for analyzing each team's roster. 

Any questions @hardcommitoneself ?

**Comment by hardcommitoneself** [comment]
@barrytarter

How can we get average `Height` of team? I'd like to know the formula.

**Comment by barrytarter** [comment]
@hardcommitoneself sure.

In the US we use height measurements that look like this 5'9 (or sometimes like 5-9 or 5'9" or 5"9).  In any of those formats the leading number (e.g. "5") is the number of feet and the 2nd number (e.g. "9") is the inches.

You would first convert the feet to inches and then add them together, so that 5 feet = 60 inches (as 1 ft = 12 inches) and then combine it with the 2nd number, e.g. 69 inches.

Next for the team, you'd average all those numbers together.  Does that make sense?

**Comment by hardcommitoneself** [comment]
Thanks, @barrytarter 

That's totally make sense!

**Comment by barrytarter** [comment]
@hardcommitoneself Can you share a CSV of the analysis data for the sample teams?

https://artuathletics.com/sports/mens-soccer/roster
https://asugrizzlies.com/sports/mens-soccer/roster
https://aupanthers.com/sports/mens-soccer/roster
[https://adrianbulldogs.com/sports/msoc/roster ](https://adrianbulldogs.com/sports/msoc/roster%C2%A0)
https://www.albertusfalcons.com/sports/msoc/2022-23/roster
https://gobrits.com/sports/mens-soccer/roster
https://albrightathletics.com/sports/mens-soccer/roster
https://alfredstate.prestosports.com/sports/msoc/2022-23/roster
https://gosaxons.com/sports/mens-soccer/roster
https://alicelloydeagles.com/sports/msoc/2022-23/roster
https://www.ahcbulldogs.com/sports/msoc/2022-23/roster
https://www.allegany.edu/athletics/mens-soccer.html
https://alleghenygators.com/sports/mens-soccer/roster
https://sccstorm.com/sports/msoc/2022-23/roster
https://almascots.com/sports/msoc/2022-23/roster
https://auwolves.com/sports/mens-soccer/roster
https://www.aicyellowjackets.com/sports/msoc/2022-23/roster
https://www.arcbeavers.com/sports/msoc/2022-23/roster

**Comment by hardcommitoneself** [comment]
@barrytarter

![image](https://user-images.githubusercontent.com/104041595/198753251-5f4eb424-f46b-418e-9ffc-4e36ecbb8b97.png)
Please check it.

**Comment by barrytarter** [comment]
@hardcommitoneself great work so far. We are going to pause the work on this one now until we have the roster link data ready.  

Instead, you'll switch over to https://github.com/EXACTsports/MotiveMob/ for the next few weeks to build the back-end infrastructure for the application.  I'll share details in a separate issue.
